### ISSUE TITLE
Debounce errors in live mode

### ISSUE THREAD

**Issue by natew** [steelbrain/steel-flint#22]
During live mode we should have a delay to avoid error flickering. My thoughts are ~500ms+ so you can type with a little delay and not "worry" about the flickering.

It's a big phycological thing for me at least that I have time to think as I'm typing, and once the red flickers up it sort of interrupts my thought.

It's also important to have quick feedback of course. We could get more smart about it in the future.

**Comment by steelbrain** [comment]
Going to make that delay a config
