### ISSUE TITLE
Color picker offset

### ISSUE THREAD

**Issue by natew** [steelbrain/steel-flint#28]
![image](https://cloud.githubusercontent.com/assets/12100/12593184/9928ce72-c424-11e5-94df-54ca6adfec4f.png)

![image](https://cloud.githubusercontent.com/assets/12100/12593190/a191774e-c424-11e5-88fe-07283c0319c4.png)

**Comment by steelbrain** [comment]
Can you please post your font size?

**Comment by steelbrain** [comment]
Fixed
