### ISSUE TITLE
Number drag underlines off in Mac

### ISSUE THREAD

**Issue by natew** [steelbrain/steel-flint#29]
FiraCode font. Tried to get some relevant info:

![image](https://cloud.githubusercontent.com/assets/12100/12593204/b8f78ac2-c424-11e5-80bc-5da52fc4c6f4.png)

![image](https://cloud.githubusercontent.com/assets/12100/12593225/cb4cb2ce-c424-11e5-9089-4686ade4961f.png)

**Comment by natew** [comment]
https://v.usetapes.com/jnfuIImXLo

**Comment by steelbrain** [comment]
Fixed in both number-range and intelli-colorpicker
