### ISSUE TITLE
Change cursor to ew-resize

### ISSUE THREAD

**Issue by natew** [steelbrain/steel-flint#30]
`cursor: ew-resize` shows left + right, right now it's showing just right.

**Comment by steelbrain** [comment]
It actually shows it based on your movement, if you move left from the initial point, it'll show a left arrow, if you move right from initial point, it'll show a right arrow

**Comment by natew** [comment]
One thing I noticed: it is always right pointing when to the right of the number, but if you drag far right then back left, it starts going down but cursor shows wrong directions.

https://v.usetapes.com/ndGgBHcCq1

**Comment by steelbrain** [comment]
I think I'm gonna use `ew-resize` for both directions
