### ISSUE TITLE
Number drags / underlines work with and without option key

### ISSUE THREAD

**Issue by natew** [steelbrain/steel-flint#31]
For me, I can see the underlines and can drag even with option key off, which I would want to be off (perhaps configurable but thats very low priority).

**Comment by steelbrain** [comment]
It actually shows it based on your movement, if you move left from the initial point, it'll show a left arrow, if you move right from initial point, it'll show a right arrow

**Comment by steelbrain** [comment]
It's already done, there's a config for it on both packages which is enabled by default, you should not be able to click colors or drag numbers unless you hold down the key

**Comment by natew** [comment]
Working!
