### ISSUE TITLE
Color picker changing opacity on Hex

### ISSUE THREAD

**Issue by natew** [steelbrain/steel-flint#33]
Should convert to RGBA (doesn't need to convert back though!)

![image](https://cloud.githubusercontent.com/assets/12100/12593340/7168023a-c425-11e5-9545-4622556bbca1.png)

**Comment by steelbrain** [comment]
If I had to guess, this is an issue with the color picker package

**Comment by steelbrain** [comment]
Workarounded by the latest intelli-colorpicker release
