### ISSUE TITLE
Build color underline on flint mode using intelli-colorpicker

### ISSUE THREAD

**Issue by ncammarata** [steelbrain/steel-flint#37]
the background is really distracting, we should use the underline, and only on press of options

**Comment by steelbrain** [comment]
Well the background is done by the pigments package. We could remove the pigments package and do the text underlines by ourself in intelli-colorpicker package.

**Comment by ncammarata** [comment]
yeah, that seems sensible. Pigments is also huge

**Comment by steelbrain** [comment]
- [x] Remove pigments as a dependency from this package
- [x] Update intelli-colorpicker to show underlines of colors

**Comment by steelbrain** [comment]
@ncammarata The `pigments` package is not going to be removed automatically. You'll have to remove it yourself, also upgrade your `intelli-colorpicker` package
