### ISSUE TITLE
Notes on autocomplete

### ISSUE THREAD

**Issue by natew** [steelbrain/steel-flint#40]
Ok, just to have these here:
- [ ] Should avoid autocompleting things that are already set
  - [ ] Style keys
  - [x] Style blocks
- [x] Should trigger after typing $ in view
- [ ] Should show autocomplete once you tab into a style block
- [ ] Some missing attributes: borderRadius, transform, etc

:)

**Comment by steelbrain** [comment]
> Some missing attributes: borderRadius, transform, etc

I'm gonna need all help I can get on this. We have a [`autocomplete-styles.js`](https://github.com/flintjs/flintprivate/blob/1150410cd63ec68b5f3f75a56e609724853fa5d3/packages/flint/runner/autocomplete-styles.js) that needs to be filled with various styles and their possible options.

**Comment by steelbrain** [comment]
Outdated since v2.0.0
