### ISSUE TITLE
autocomplete attributes are off

### ISSUE THREAD

**Issue by ncammarata** [steelbrain/steel-flint#46]
https://v.usetapes.com/qkQisJcd2z

should be

![image](https://cloud.githubusercontent.com/assets/204989/12770288/1359b10c-c9d4-11e5-882f-70cbfe79292e.png)

with the number selected so its easy to change. Later on we can make it so one more tab adds another attribute

**Comment by steelbrain** [comment]
Closing, based on https://github.com/atom/autocomplete-plus/issues/661
