### ISSUE TITLE
Cmd + n doesn't work to create a new file

### ISSUE THREAD

**Issue by ncammarata** [steelbrain/steel-flint#47]
throws

![image](https://cloud.githubusercontent.com/assets/204989/12772558/094df2d2-c9e7-11e5-8595-4cd9b5f47fa8.png)

which is
![image](https://cloud.githubusercontent.com/assets/204989/12772555/0362d19e-c9e7-11e5-83f0-b03cfab88b1d.png)

**Comment by steelbrain** [comment]
Outdated since v2.0.0
