### ISSUE TITLE
Autocomplete with error

### ISSUE THREAD

**Issue by ncammarata** [steelbrain/steel-flint#48]
![image](https://cloud.githubusercontent.com/assets/204989/12772886/dff2f4c4-c9ea-11e5-8838-68e095b9265a.png)

in the common situation of making a new line for a new style, typing f technically creates a syntax error, killing the autocomplete

**Comment by steelbrain** [comment]
Currently the way we generate autocompletes is we transform text with babel and extract locations of views. If there is a syntax error, babel halts and does not tell us anything about the views so we can't autocomplete.

@natew Is there a way around it?

**Comment by ncammarata** [comment]
Is it possible to get whether you're still in the a bracket range? It seems like as long as you know you're in a style (from babel) it makes sense to go "off the network" and just be smart about guessing as long as you're in the style so it can handle these situations

**Comment by steelbrain** [comment]
Outdated since v2.0.0
