### ISSUE TITLE
Connection always shows idle in my main project

### ISSUE THREAD

**Issue by AriaFallah** [steelbrain/steel-flint#49]
I can get it to work for new projects, but not my current one. Even if it's not working for the newer projects, I can always reload the atom window and it'll show `connected` and work.

Not sure what's causing it. I'm on the latest `steel-flint` and the latest `flint`

https://github.com/AriaFallah/formulagrid

**Comment by steelbrain** [comment]
Investigating

**Comment by steelbrain** [comment]
@AriaFallah It only recognizes flint projects at root, so if you run Atom at the root of that repo, it won't be detected, not even by the flint cli

```
/t/formulagrid ❯❯❯ flint
Not in flint app!
```

If you want it to work, either start atom in `website` directory or move your app a level up

**Comment by AriaFallah** [comment]
@steelbrain oh I see! Thank you for so rapidly responding.
