### ISSUE TITLE
Proposition: range/color saves even if not in live mode

### ISSUE THREAD

**Issue by ncammarata** [steelbrain/steel-flint#53]
I can't think of many times I use the number dragger or color picker when I'm not fine tuning. Thoughts @steelbrain @natew 

Also, I'm using the steel-flint repo as a catchall for these high level issues rather than distribute between the various components. Let me know if you want me to relocate this @steelbrain!

**Comment by steelbrain** [comment]
Number-Range or the color picker packages do not save automatically. If I had to guess, you have enabled atom auto save which saves the file each time the program is switched

**Comment by ncammarata** [comment]
oh, I'm suggesting that we save when you use either of the direct manipulation plugins. It wouldn't actually save the file, just websocket to the compiler

**Comment by steelbrain** [comment]
But doesn't that defeat the purpose of disabling live preview?

**Comment by ncammarata** [comment]
well, the downside of live preview is its bad when writing functions and it's constantly running them. I think 99% of the time for number and color I want a live preview

**Comment by ncammarata** [comment]
I could see the downside here, which is why it's a proposition, but I do think from most Flint user's I've talked to they almost all want this

**Comment by steelbrain** [comment]
Outdated since v2.0.0
