### ISSUE TITLE
Color pick css colors

### ISSUE THREAD

**Issue by ncammarata** [steelbrain/steel-flint#65]
![image](https://cloud.githubusercontent.com/assets/204989/13124656/4ae0892c-d576-11e5-9691-c7234613def4.png)

The 100 most common ones will bring us a long way. This is important because we autogenerate a color with your new app

**Comment by steelbrain** [comment]
Does the color-picker (when invoked via it's own command) recognize named colors?

**Comment by ncammarata** [comment]
no, which is why I used pigments for this before (and had both color picker and pigments running, which is bad). we should probably use our own simple detection

**Comment by steelbrain** [comment]
Outdated since v2.0.0
