### ISSUE TITLE
Cannot read property els

### ISSUE THREAD

**Issue by natew** [steelbrain/steel-flint#73]
Tried a few different views on right click:

![image](https://cloud.githubusercontent.com/assets/12100/13168849/9729cd3c-d695-11e5-9254-d94c132aacfc.png)

```
Uncaught (in promise) TypeError: Cannot read property 'els' of undefined
    at /Users/nw/.atom/packages/motion/lib/editor.js:72:29
    at [object Generator].next (native)
    at step (/Users/nw/.atom/packages/motion/lib/editor.js:9:273)
```

**Comment by steelbrain** [comment]
Fixed by https://github.com/motion/atom/commit/7efc753437e06d5276acbebed1ee9b3d56f3aafe in #72
