### ISSUE TITLE
One for Sublime

### ISSUE THREAD

**Issue by nikoloza** [steelbrain/steel-flint#80]
Hello @steelbrain , 

Are you also planning to make a Sublime Text plugin for Motion?

Thanks

**Comment by steelbrain** [comment]
Hi @nikoloza, the latest version of Motion doesn't really require this and at this point this is just some extra sugar for the editor.

The only feature offered by this package at the moment is that if you write `import component from '$component'`, it replaces it with the exact path of the file from the root relative to the callee like `import component from '../../component'`.

So Motion works very well without it, you just have to write the abs path yourself. With that said, I don't personally use Sublime text and am not really familiar with it's APIs. I might look into creating one if there's a HUGE demand for it :)

**Comment by nikoloza** [comment]
@steelbrain great answer, thanks :)
